language: python
python:
  - "3.6"
branches:
  only:
  - master
env:
  - TEMPLATE=concourse-web.template
jobs:
  include:
    - stage: Remove previous stack
      script:
        - aws cloudformation delete-stack --stack-name concourse
        - aws cloudformation wait stack-delete-complete
    - stage: Upload new stack template
      script: aws s3 cp ${TEMPLATE} s3://${S3_BUCKET}/
    - stage: Deploy new stack
      script: |
        aws cloudformation create-stack --stack-name concourse 
        --template-url=https://${S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com/${TEMPLATE} 
        --parameters ParameterKey=VpcId,ParameterValue=${VPC_ID} 
          ParameterKey=KeyName,ParameterValue=${KEYPAIR_NAME} 
          ParameterKey=Subnets,ParameterValue=${SUBNETS} 
          ParameterKey=DBUser,ParameterValue=${DB_USER} 
          ParameterKey=DBPassword,ParameterValue=${DB_PASSWORD}